apiVersion: v1
kind: Pod
metadata:
  name: pod-apache  #10.244.1.31
spec:
  containers:
  - name: my-apache
    image: httpd

---
apiVersion: v1
kind: Pod
metadata:
  name: pod-nginx  #10.244.1.30
spec:
  containers:
  - name: my-nginx
    image: nginx

